;;;; src/codex-oauth.lisp — Native Codex OAuth browser-link flow for cl-llm

(in-package #:cl-llm/codex-oauth)

(defvar *codex-oauth-client-id* "")
(defvar *codex-oauth-authorize-endpoint* "https://auth.openai.com/oauth/authorize")
(defvar *codex-oauth-token-endpoint* "https://auth.openai.com/oauth/token")
(defvar *codex-oauth-redirect-uri* "https://localhost/callback")
(defvar *codex-oauth-scope* "openid profile email offline_access")
(defvar *codex-oauth-store-path*
  (merge-pathnames ".clawmacs/auth/codex-oauth.json" (user-homedir-pathname)))

(defun %now () (get-universal-time))

(defun %random-string (&optional (len 48))
  (let ((alphabet "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~")
        (s (make-string len)))
    (dotimes (i len s)
      (setf (char s i) (char alphabet (random (length alphabet)))))))

(defun %read-json-file (path)
  (when (probe-file path)
    (with-open-file (in path :direction :input)
      (let ((txt (make-string (file-length in))))
        (read-sequence txt in)
        (com.inuoe.jzon:parse txt)))))

(defun %chmod-600 (path)
  #+sbcl (ignore-errors (sb-posix:chmod (namestring path) #o600))
  #-sbcl nil)

(defun %write-json-file-600 (path ht)
  (ensure-directories-exist path)
  (with-open-file (out path :direction :output :if-exists :supersede :if-does-not-exist :create)
    (write-string (com.inuoe.jzon:stringify ht) out))
  (%chmod-600 path)
  path)

(defun %load-session () (%read-json-file *codex-oauth-store-path*))

(defun %get-int (ht key)
  (let ((v (and ht (gethash key ht))))
    (cond ((integerp v) v)
          ((stringp v) (parse-integer v :junk-allowed t))
          (t nil))))

(defun %query-param (url key)
  (let* ((qpos (position #\? url))
         (hpos (position #\# url))
         (query (and qpos (subseq url (1+ qpos) (or hpos (length url))))))
    (when query
      (dolist (pair (cl-ppcre:split "&" query))
        (let ((eq (position #\= pair)))
          (when eq
            (let ((k (subseq pair 0 eq))
                  (v (subseq pair (1+ eq))))
              (when (string= k key)
                (return-from %query-param (quri:url-decode v))))))))))

(defun %extract-code+state (s)
  (let ((input (string-trim '(#\Space #\Tab #\Newline) s)))
    (if (or (search "http://" input :test #'char-equal)
            (search "https://" input :test #'char-equal))
        (values (%query-param input "code") (%query-param input "state"))
        (let ((p (position #\# input)))
          (if p
              (values (subseq input 0 p) (subseq input (1+ p)))
              (values nil nil))))))

(defun %expires-at (token-ht)
  (let ((expires-in (%get-int token-ht "expires_in")))
    (when expires-in (+ (%now) expires-in))))

(defun %store-session-from-token (token-ht &key state verifier)
  (let ((ht (make-hash-table :test 'equal)))
    (setf (gethash "linked" ht) t)
    (setf (gethash "updated_at" ht) (%now))
    (setf (gethash "access_token" ht) (gethash "access_token" token-ht))
    (setf (gethash "refresh_token" ht) (gethash "refresh_token" token-ht))
    (setf (gethash "token_type" ht) (or (gethash "token_type" token-ht) "Bearer"))
    (setf (gethash "scope" ht) (or (gethash "scope" token-ht) *codex-oauth-scope*))
    (setf (gethash "expires_at" ht) (%expires-at token-ht))
    (setf (gethash "last_state" ht) state)
    (setf (gethash "code_verifier" ht) verifier)
    (%write-json-file-600 *codex-oauth-store-path* ht)))

(defun %token-request (params)
  (let* ((body (quri:url-encode-params params))
         (resp (dexador:post *codex-oauth-token-endpoint*
                             :headers '(("Content-Type" . "application/x-www-form-urlencoded"))
                             :content body)))
    (com.inuoe.jzon:parse resp)))

(defun codex-oauth-start (&key client-id)
  (let* ((cid (or client-id *codex-oauth-client-id*))
         (state (%random-string 32))
         (verifier (%random-string 64)))
    (when (or (null cid) (string= (string-trim " " cid) ""))
      (error "Codex OAuth client id missing. Set cl-llm/codex-oauth:*codex-oauth-client-id*"))
    (let ((pending (or (%load-session) (make-hash-table :test 'equal))))
      (setf (gethash "pending_state" pending) state)
      (setf (gethash "pending_verifier" pending) verifier)
      (setf (gethash "updated_at" pending) (%now))
      (%write-json-file-600 *codex-oauth-store-path* pending))
    (let* ((params `(("response_type" . "code")
                     ("client_id" . ,cid)
                     ("redirect_uri" . ,*codex-oauth-redirect-uri*)
                     ("scope" . ,*codex-oauth-scope*)
                     ("state" . ,state)
                     ("code_challenge" . ,verifier)
                     ("code_challenge_method" . "plain")))
           (auth-url (format nil "~A?~A" *codex-oauth-authorize-endpoint* (quri:url-encode-params params))))
      (list :auth-url auth-url
            :state state
            :instructions "Open URL, approve, then paste full redirect URL to /codex_link"))))

(defun codex-oauth-complete (redirect-or-code-state &key client-id)
  (let* ((cid (or client-id *codex-oauth-client-id*))
         (session (%load-session))
         (expected-state (and session (gethash "pending_state" session)))
         (verifier (and session (gethash "pending_verifier" session))))
    (when (or (null cid) (string= (string-trim " " cid) ""))
      (error "Codex OAuth client id missing. Set cl-llm/codex-oauth:*codex-oauth-client-id*"))
    (multiple-value-bind (code state) (%extract-code+state redirect-or-code-state)
      (cond
        ((or (null code) (string= code ""))
         (list :ok nil :message "Malformed input: missing code."))
        ((or (null state) (string= state ""))
         (list :ok nil :message "Malformed input: missing state."))
        ((or (null expected-state) (not (string= state expected-state)))
         (list :ok nil :message "OAuth state mismatch. Run /codex_login again."))
        (t
         (handler-case
             (let ((token-ht (%token-request
                              `(("grant_type" . "authorization_code")
                                ("client_id" . ,cid)
                                ("code" . ,code)
                                ("redirect_uri" . ,*codex-oauth-redirect-uri*)
                                ("code_verifier" . ,(or verifier ""))))))
               (if (gethash "access_token" token-ht)
                   (progn
                     (%store-session-from-token token-ht :state state :verifier verifier)
                     (list :ok t :message "Codex OAuth linked successfully." :expires-at (%expires-at token-ht)))
                   (list :ok nil :message "Token exchange failed: no access_token.")))
           (error (e)
             (list :ok nil :message (format nil "Token exchange failed: ~A" e)))))))))

(defun codex-oauth-refresh (&key client-id)
  (let* ((cid (or client-id *codex-oauth-client-id*))
         (session (%load-session))
         (refresh (and session (gethash "refresh_token" session))))
    (when (or (null cid) (string= (string-trim " " cid) ""))
      (error "Codex OAuth client id missing. Set cl-llm/codex-oauth:*codex-oauth-client-id*"))
    (unless (and refresh (not (string= refresh "")))
      (error "No refresh token available. Use /codex_login then /codex_link."))
    (let ((token-ht (%token-request `(("grant_type" . "refresh_token")
                                      ("client_id" . ,cid)
                                      ("refresh_token" . ,refresh)))))
      (unless (gethash "access_token" token-ht)
        (error "Refresh failed: no access_token."))
      (%store-session-from-token token-ht
                                 :state (gethash "last_state" session)
                                 :verifier (gethash "code_verifier" session))
      (%load-session))))

(defun codex-oauth-access-token (&key client-id)
  (let ((session (%load-session)))
    (cond
      ((and session
            (stringp (gethash "access_token" session))
            (> (length (gethash "access_token" session)) 0)
            (let ((exp (%get-int session "expires_at")))
              (or (null exp) (> exp (+ (%now) 30)))))
       (gethash "access_token" session))
      ((and session (gethash "refresh_token" session))
       (let ((refreshed (codex-oauth-refresh :client-id client-id)))
         (or (gethash "access_token" refreshed)
             (error "Codex OAuth refresh failed. Use /codex_login."))))
      (t
       (error "Codex OAuth missing/invalid. Use /codex_login then /codex_link.")))))

(defun codex-oauth-status ()
  (let* ((session (%load-session))
         (linked (and session (stringp (gethash "access_token" session))
                      (> (length (gethash "access_token" session)) 0)))
         (expires-at (%get-int session "expires_at"))
         (expired (and expires-at (<= expires-at (%now)))))
    (list :linked (and linked t)
          :expires-at expires-at
          :expired (and expired t)
          :has-refresh-token (and session (stringp (gethash "refresh_token" session))
                                  (> (length (or (gethash "refresh_token" session) "")) 0))
          :store-path (namestring *codex-oauth-store-path*))))

(defun codex-oauth-status-string ()
  (destructuring-bind (&key linked expires-at expired has-refresh-token store-path &allow-other-keys)
      (codex-oauth-status)
    (with-output-to-string (s)
      (format s "Codex OAuth status~%")
      (format s "- linked: ~A~%" (if linked "yes" "no"))
      (format s "- expires_at: ~A~%" (or expires-at "unknown"))
      (format s "- expired: ~A~%" (if expired "yes" "no"))
      (format s "- refresh token: ~A~%" (if has-refresh-token "present" "missing"))
      (format s "- store: ~A~%" store-path))))